const sympdata = {
  itching:
    "Itchy skin is an irritating sensation that makes you want to scratch. It's also called pruritus (proo-RIE-tus). Itchy skin is often caused by dry skin and is common in older adults, as skin tends to become drier with age.  Depending on the cause of your itchiness, your skin may look no different than usual or it may be inflamed, rough or have bumps. Repeated scratching can cause raised thick areas of skin that might bleed or become infected.  Many people find relief with self-care measures such as moisturizers, gentle cleansers and lukewarm baths. Long-term relief requires identifying and treating the cause of itchy skin. Common treatments are medicated creams, moist dressings and anti-itch medicines taken by mouth.",
  skin_rash:
    "A rash is any area of irritated or swollen skin on your body. Rashes are often itchy and painful and can appear differently on different skin tones. While they are often described as red, on darker skin tones they may be purple, gray, or white.  noda_skin_eruption : A rash accompanied by swollen lymph nodes usually stems from a viral infection, such as measles, chickenpox, or mononucleosis.  A rash is an inflammatory response that causes changes to your skin, such as redness, itching, blistering, or scaly or raised skin patches. Rashes can be the result of a variety of things.  Lymph nodes are part of your lymphatic system. They filter fluids in your body and return them to your circulation system for disposal. They also house infection-fighting cells.  You can’t typically feel your lymph nodes when you’re healthy, but they can become swollen and tender when your body is having an immune response.",
  continuous_sneezing:
    "Nonallergic rhinitis involves chronic sneezing or a congested, drippy nose with no apparent cause. Nonallergic rhinitis symptoms are similar to those of hay fever (allergic rhinitis), but with none of the usual evidence of an allergic reaction.  Nonallergic rhinitis can affect children and adults. But it's more common after age 20. Triggers of nonallergic rhinitis symptoms vary and can include certain odors or irritants in the air, weather changes, some medications, certain foods, and chronic health conditions.  A diagnosis of nonallergic rhinitis is made after an allergic cause is ruled out. This may require allergy skin or blood tests.  shivering :our body regulates its responses to heat, cold, stress, infection, and other conditions without any conscious thought. You sweat to cool the body when you get overheated, for example, but you don’t have to think about it. And when you get cold, you shiver automatically.  A shiver is caused by your muscles tightening and relaxing in rapid succession. This involuntary muscle movement is your body’s natural response to getting colder and trying to warm up.  Responding to a cold environment, however, is only one reason why you shiver. Illness and other causes can also make you shake and shiver.",
  chills:
    "Chills are your body's way of raising its core temperature. Cold temperatures, viruses, infections and other illnesses can bring on chills. When you shiver, your muscles relax and contract. This involuntary movement warms your body. Chills and fever often go together. But not everyone with a fever gets chills. And you can get chills with no fever.",
  joint_pain:
    "Joint discomfort is common and usually felt in the hands, feet, hips, knees, or spine. Pain may be constant or it can come and go. Sometimes the joint can feel stiff, achy, or sore. Some patients complain of a burning, throbbing, or grating sensation. In addition, the joint may feel stiff in the morning but loosen up and feel better with movement and activity. However, too much activity could make the pain worse.  Joint pain may affect the function of the joint, and can limit a person’s ability to do basic tasks. Severe joint pain can affect the quality of life. Treatment should focus not only on pain but also on the affected activities and functions.",
  stomach_pain:
    "Abdominal pain has many causes, some more serious than others. What feels like a stomachache may be coming from another organ in your abdomen, or from outside of your digestive system. Always seek medical care if your abdominal pain is unexplained, persistent or severe.",
  stomach_pain:
    "Abdominal pain has many causes, some more serious than others. What feels like a stomachache may be coming from another organ in your abdomen, or from outside of your digestive system. Always seek medical care if your abdominal pain is unexplained, persistent or severe.",
  acidity:
    "The food we eat goes into our stomach through the esophagus. The gastric glands in your stomach create acid, which is necessary to digest the food. When the gastric glands create more acid than needed for the digestion process, you can feel a burning sensation below the breastbone. This condition is commonly known as acidity.  Acidity, also called acid reflux, is a condition that is characterized by heartburn that is felt around the lower chest area. It is a common condition that occurs when stomach acid flows back up into the food pipe.  The most common acid reflux symptom is a burning sensation in the chest or pain. While most people suffer in pain, they do not realize that poor lifestyle choices are the primary reason behind acidity.  When acidity symptoms occur more than twice a week, your doctor may diagnose you with Gastroesophageal reflux disease or GERD. Chronic acidity may lead to serious risks that include:      Esophagus damage: Esophagus is the tube that connects your mouth to your stomach and when acid moves back up and enters the esophagus, it sets the stage for esophageal ulcers, oesophagitis, esophageal strictures, and Barrett’s Oesophagus.     Esophagus cancer: There is an increased risk of esophagus cancer, which is more likely if you have a history of the condition in the family.     Cavities/tooth decay: Acid reflux can wear down the enamel of your teeth and lead to cavities.",

  ulcers_on_tongue:
    "Ulcer is an idiopathic condition you can not directly come to a single cause of it. I think as per your symptoms you may have  sharp edges of lower and upper molars. You should also have a regular diet to avoid constipation and other indigestion difficulties to avoid heat and this will indirectly reduce your ulcers. Have ninefol tab twice a day and apply amlenox gel twice a day",
  muscle_wasting:
    "There are three types of muscle atrophy: physiologic, pathologic, and neurogenic  Physiologic atrophy is caused by not using the muscles enough. This type of atrophy can often be reversed with exercise and better nutrition. People who are most affected are those who:      Have seated jobs, health problems that limit movement, or decreased activity levels     Are bedridden     Cannot move their limbs because of stroke or other brain disease     Are in a place that lacks gravity, such as during space flights ",
  vomitng:
    "ausea and vomiting are not diseases, but rather are symptoms of many different conditions, such as infection , food poisoning, motion sickness, overeating, blocked intestine, illness, concussion or brain injury, appendicitis and migraines. Nausea and vomiting can sometimes be symptoms of more serious diseases such as heart attacks, kidney or liver disorders, central nervous system disorders, brain tumors, and some forms of cancer.",
  burning_micturition:
    "f you think you might have a UTI, don't worry. Diagnosing one requires a simple urinalysis. You urinate into a cup, and your clinician examines the urine for signs of infection. The standard course of treatment is three to five days of antibiotics.  In some cases, especially if your infections keep coming back, your practitioner may order a urine culture, a specific test for UTIs. A culture identifies the bacteria causing your infection so your clinician can choose the most effective antibiotic to treat it. The results of a urine culture are typically not available for two to four days.",
  weight_gain:
    "Gaining weight when you are not trying to do so can have many causes.  Metabolism slows down as you age. This can cause weight gain if you eat too much, eat the wrong foods, or do not get enough exercise.  Drugs that can cause weight gain include:      Birth control pills     Corticosteroids     Some drugs used to treat bipolar disorder, schizophrenia, and depression     Some drugs used to treat diabetes",
  anxiety:
    "Anxiety is a feeling of fear, dread, and uneasiness. It might cause you to sweat, feel restless and tense, and have a rapid heartbeat. It can be a normal reaction to stress. For example, you might feel anxious when faced with a difficult problem at work, before taking a test, or before making an important decision. It can help you to cope. The anxiety may give you a boost of energy or help you focus. But for people with anxiety disorders, the fear is not temporary and can be overwhelming.",
  cold_hands_and_feets:
    "Our bodies are designed to regulate our temperature. When it's cold outside, your body makes sure to keep the blood flowing to your core and vital organs to keep them warm. This can change the amount of blood flow to your hands and feet, making them feel cold. This is normal. The blood vessels in your hands and feet constrict (spasm) when it’s cold, to prevent heat loss from your core.  Some people tend to have colder feet and hands naturally, without an underlying disease. It’s a fairly common conditionTrusted Source. When your hands and feet naturally tend to get cold, you may just need to take extra precautions in cold weather to protect them.  But if your cold feet and hands are constantly bothersome, or if you notice additional symptoms, such as color changes in your fingers, there are more things you can do. ",
  mood_swings:
    "Many people have days where they feel sad or overjoyed. When shifts in mood don’t affect your daily schedule regularly, they’re generally considered to be typical.  On the other hand, if you have large shifts from happiness to depression on a regular basis, you should speak with your doctor. They can discuss the possible reasons you’re experiencing them.  Some causes of rapid changes in behavior can be related to mental health, hormones, substance use, or other health conditions.",
  spotting_urination:
    "Blood in your urine is called hematuria. The amount may be very small and only detected with urine tests or under a microscope. In other cases, the blood is visible. It often turns the toilet water red or pink. Or, you may see spots of blood in the water after urinating.",
  fatigue:
    "Fatigue is a term used to describe an overall feeling of tiredness or lack of energy. It isn’t the same as simply feeling drowsy or sleepy. When you’re fatigued, you have no motivation and no energy. Being sleepy may be a symptom of fatigue, but it’s not the same thing.  Fatigue is a common symptom of many medical conditions that range in severity from mild to serious. It’s also a natural result of some lifestyle choices, such as lack of exercise or poor diet.  If your fatigue doesn’t resolve with proper rest and nutrition, or you suspect it’s caused by an underlying physical or mental health condition, see your doctor. They can help diagnose the cause of your fatigue and work with you to treat it. ",
  weight_gain:
    "Unintentional weight gain occurs when you put on weight without increasing your consumption of food or liquid and without decreasing your activity. This occurs when you’re not trying to gain weight. It’s often due to fluid retention, abnormal growths, constipation, or pregnancy.  Unintentional weight gain can be periodic, continuous, or rapid.  Periodic unintentional weight gain includes regular fluctuations in weight. One example of unintentional weight gain is experienced during a woman’s menstrual cycle. Periodic, but longer-term unintentional weight gain is often the result of pregnancy, which lasts nine months.  Rapid unintentional weight gain may be due to medication side effects. Many cases of unintentional weight gain are harmless. But some symptoms experienced along with rapid weight gain may signal a medical emergency.",
  weight_loose:
    "Weight loss is not the answer to every health problem, but if your doctor recommends it, there are tips to help you lose weight safely. A steady weight loss of 1 to 2 pounds per week is recommended for the most effective long-term weight management.  That said, many eating plans designed to help you lose weight leave you feeling hungry or unsatisfied, or they cut out major food groups and are not sustainable. These are major reasons why you might find it hard to stick to a healthier eating plan. ",
  restlessness:
    "Restlessness is feeling the need to constantly move, being unable to calm your mind, or a combination of the two. You may also experience hyperactivity, anxiety, palpitations, agitation, or insomnia.  People with motor restlessness often feel they have cramps in their arms or legs whenever they're not moving. They may have difficulty sitting still while at work or relaxing at home, or have the urge to tap their hands or feet. Other people may experience mental restlessness, and have difficulty accomplishing tasks, managing time, or falling asleep at night.  Restlessness can be from stimulating medications, stopping medications, or drinking too much caffeine in a day. Hormonal imbalances, neurologic problems, pain, or mental health conditions can also cause restlessness.",
  lethargy:
    "Lethargy is a general state of fatigue that involves a lack of energy and motivation for physical and mental tasks.  Some simple causes, such as overexertion or not getting enough sleep, can leave a person feeling lethargic. In other cases, an underlying health condition may cause long-term lethargy and fatigue.  It may be necessary to see a doctor to determine the cause of lethargy if it lasts for a longer period of time. Getting a full diagnosis can help identify any underlying issues and work toward treatment.  Keep reading to learn more about the possible causes of lethargy, how to treat them, and when to see a doctor. ",
};
